apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testeste-blog-simple"
  annotations:
    github.com/project-slug: sjflausino/testeste-blog-simple
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: ci.yml
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/demo"
